#!/bin/bash -ex

source /usr/local/src/canvas.conf

GEMOPTS='--no-document'

# install gems
[ "$FAB_HTTP_PROXY" ] && export http_proxy=$FAB_HTTP_PROXY

gem install $GEMOPTS bundler -v '2.1.1' --force
rm /usr/local/rbenv/versions/*/lib/ruby/gems/*/specifications/default/bundler*.gemspec
gem uninstall bundler -v '>2.1.1' -aIx
gem install $GEMOPTS psych
gem install $GEMOPTS activesupport
unset http_proxy

