#!/bin/bash -ex

source /usr/local/src/canvas.conf

n 14.17.0

# Reinstall previous previous version; then update to workaround weird bug
# See: https://github.com/yarnpkg/yarn/issues/8253#issuecomment-667525692
apt-get install -y --allow-downgrades yarn=1.22.1-1
yarn -v
apt-get install -y yarn
