#!/bin/bash -ex

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list

apt-get -y install apt-transport-https
apt-get -y update
apt-get -y install yarn
