#!/bin/bash -ex

source /usr/local/src/canvas.conf

# get db_pass set by common/rails and update canvas.conf
DB_PASS=$(grep password: $WEBROOT/config/database.yml | head -n 1 | awk '{print $2}')
sed -i "s|DB_PASS=.*|DB_PASS=$DB_PASS|" /usr/local/src/canvas.conf

# remove common/rails webroot
rm -rf $WEBROOT

