#!/bin/bash -ex

source /usr/local/src/canvas.conf

/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# create queue database and set permissions
$MYSQL_ADMIN create $DB_QUEUE --default-character-set=utf8;
$MYSQL_BATCH --execute "grant all privileges on $DB_QUEUE.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

