#!/bin/bash -ex

source /usr/local/src/canvas.conf

# download and set branch to version
URL="https://github.com/instructure/canvas-lms.git"

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
git clone $URL $WEBROOT --depth=1 -b prod
unset HTTP_PROXY

cd $WEBROOT

# tweak footer
CONF=$WEBROOT/app/views/layouts/application.html.erb
sed -i "s|</footer>|<div id='turnkey-credit' style='text-align:center;padding-top:20px;'><a href='https://www.turnkeylinux.org/canvas'>Canvas Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a></div>\n    </footer>|" $CONF
