#!/bin/bash -ex

source /usr/local/src/canvas.conf

# setup database config
cat >$WEBROOT/config/database.yml<<EOF
production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: $DB_NAME
  username: $DB_USER
  password: $DB_PASS
  timeout: 5000
  queue:
    adapter: postgresql
    encoding: utf8
    host: localhost
    database: $DB_QUEUE
    username: $DB_USER
    password: $DB_PASS
    timeout: 5000
EOF

# setup email config
cat >$WEBROOT/config/outgoing_mail.yml<<EOF
production:
  tls: false
  enable_starttls_auto: false
  address: "localhost"
  port: "25"
  domain: "$DOMAIN"
  outgoing_address: "$ADMIN_MAIL"
  default_name: "TurnKey Canvas"
EOF

# setup domain config
cat >$WEBROOT/config/domain.yml<<EOF
production:
  domain: "$DOMAIN"
  ssl: true
EOF

# setup cache store config
cat >$WEBROOT/config/cache_store.yml<<EOF
production:
  cache_store: redis_store
EOF

cat >$WEBROOT/config/redis.yml<<EOF
production:
  servers:
  - redis://localhost
EOF

cat >$WEBROOT/config/delayed_jobs.yml<<EOF
production:
  workers:
  - queue: canvas_queue
    workers: 2
    max_priority: 10
  - queue: canvas_queue
    workers: 2

  max_run_time: 28800
  worker_max_job_count: 20
  worker_max_memory_usage: 536870912

default:
  workers:
  - queue: canvas_queue
EOF

# copy example configurations
CONFIGS="amazon_s3 file_store security external_migration"
for c in $CONFIGS; do
    cp $WEBROOT/config/$c.yml.example $WEBROOT/config/$c.yml
done

WEBROOT=/var/www/canvas
USER=www-data:www-data

# configure permissions
mkdir -p $WEBROOT/log
mkdir -p $WEBROOT/tmp/pids
mkdir -p $WEBROOT/tmp/files
mkdir -p $WEBROOT/tmp/attachment_fu
mkdir -p $WEBROOT/public/assets
mkdir -p $WEBROOT/public/stylesheets/compiled

chown -R root:www-data $WEBROOT
chown -R $USER $WEBROOT/log
chown -R $USER $WEBROOT/tmp
chown $USER $WEBROOT/config/*.yml
chown $USER $WEBROOT/config/environment.rb
chmod 640 $WEBROOT/config/*.yml

