#!/bin/bash -ex

# Download and install new 'pulsar-client' gem dependencies

# Match this version as closely as possible to the pulsar-client gem readme:
# https://github.com/instructure/pulsar-client-ruby#installation
# Closest I could get is v2.6.3 - see: https://downloads.apache.org/pulsar/
version=2.6.3

tmp=/tmp/pulsar-client
base_url=https://downloads.apache.org/pulsar
full_url=$base_url/pulsar-${version}/DEB

fatal() { echo "FATAL: $@" >&2; exit 1; }

run_gpg() {
    unset exit_code
    gpg --keyring $tmp/keyring.gpg "$@" || exit_code=$?
    case $exit_code in
        0)
            return;;
        1)
            fatal "GPG check failed.";;
        2)
            echo "Some other GPG error occurred."
            echo "Probably untrusted signature so letting it pass...";;
        *)
            fatal "Unknow/unexpected exit code: $exit_code";;
    esac
}

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    file_name=$(basename $1)
    cd $2; curl -L -f -o $file_name $PROXY $1; cd -
}

mkdir -p $tmp/DEB

# set up keyring
dl $base_url/KEYS $tmp/
run_gpg --import $tmp/KEYS || exit_code=$?

apt-get update

for deb in apache-pulsar-client.deb apache-pulsar-client-dev.deb; do
    dl $full_url/$deb $tmp/DEB/
    dl $full_url/$deb.asc $tmp
    dl $full_url/$deb.sha512 $tmp

    cd $tmp
    sha512sum -c $deb.sha512
    run_gpg --verify $deb.asc ./DEB/$deb

    apt-get install -y $tmp/DEB/$deb
done

cd ~

rm -rf $tmp
