#!/bin/bash -ex

source /usr/local/src/canvas.conf

# preset answers for automated install
export CANVAS_LMS_ADMIN_EMAIL=$ADMIN_MAIL
export CANVAS_LMS_ADMIN_PASSWORD=$ADMIN_PASS
export CANVAS_LMS_ACCOUNT_NAME="TurnKey Canvas"
export CANVAS_LMS_STATS_COLLECTION="opt-out"

# install canvas, populate database and compile assets
service redis-server start
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

cd $WEBROOT

RAILS_ENV=production bundle install --path vendor/bundle --without mysql sqlite
yarn install

CANVAS_BUILD_CONCURRENCY=1 JS_BUILD_NO_UGLIFY=true LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 RAILS_ENV=production bundle exec rake canvas:compile_assets

RAILS_ENV=production bundle exec rake db:initial_setup

cd gems/canvas_i18nliner/
npm install --unsafe-perm
cd -

mkdir -p log tmp/pids public/assets 


# stop services
service postgresql stop
service redis-server stop

unset HTTP_PROXY

# clean out installation log
rm -f $WEBROOT/log/*

