#!/bin/bash -ex

source /usr/local/src/canvas.conf

# bugfix
sed -i "/index_groups_on_wiki_id/ s/^/#/" $WEBROOT/db/migrate/20101210192618_init_canvas_db.rb

# preset answers for automated install
export CANVAS_LMS_ADMIN_EMAIL=$ADMIN_MAIL
export CANVAS_LMS_ADMIN_PASSWORD=$ADMIN_PASS
export CANVAS_LMS_ACCOUNT_NAME="TurnKey Canvas"
export CANVAS_LMS_STATS_COLLECTION="opt-out"

# install canvas, populate database and compile assets
service redis-server start

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

cd $WEBROOT

RAILS_ENV=production bundle install --path vendor/bundle --without mysql sqlite
npm install --unsafe-perm

RAILS_ENV=production bundle exec rake db:initial_setup

cd gems/canvas_i18nliner/
npm install --unsafe-perm
cd -

mkdir -p log tmp/pids public/assets public/stylesheets/compiled
touch Gemfile.lock

LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 RAILS_ENV=production bundle _1.10.5_ exec rake canvas:compile_assets

unset HTTP_PROXY

# clean out installation log
rm -f $WEBROOT/log/*

# stop services
service redis-server stop

