#!/bin/bash -ex

source /usr/local/src/canvas.conf

# preset answers for automated install
export CANVAS_LMS_ADMIN_EMAIL=$ADMIN_MAIL
export CANVAS_LMS_ADMIN_PASSWORD=$ADMIN_PASS
export CANVAS_LMS_ACCOUNT_NAME="TurnKey Canvas"
export CANVAS_LMS_STATS_COLLECTION="opt-out"

# install canvas, populate database and compile assets
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

cd $WEBROOT
bundle install --path vendor/bundle --without sqlite postgres
RAILS_ENV=production bundle exec rake db:initial_setup
bundle exec rake canvas:compile_assets

unset HTTP_PROXY

# clean out installation log
rm -f $WEBROOT/log/*

# stop services
/etc/init.d/mysql stop
/etc/init.d/redis-server stop

