#!/bin/bash -ex

# disable Aapche mod_evasive for now - see
# https://github.com/turnkeylinux/tracker/issues/1965
a2dismod evasive

source /usr/local/src/canvas.conf

YARN_CACHE=/var/cache/yarn

# preset answers for automated install
export CANVAS_LMS_ADMIN_EMAIL=$ADMIN_MAIL
export CANVAS_LMS_ADMIN_PASSWORD=$ADMIN_PASS
export CANVAS_LMS_ACCOUNT_NAME="TurnKey Canvas"
export CANVAS_LMS_STATS_COLLECTION="opt-out"

# set lang to quieten down install
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# install canvas, populate database and compile assets
service redis-server start
[ "$FAB_HTTP_PROXY" ] && export http_proxy=$FAB_HTTP_PROXY

cd $WEBROOT

# canvas needs specific version of bundler - see
# https://github.com/instructure/canvas-lms/wiki/Production-Start#bundler-and-canvas-dependencies
gem install bundler --no-document --version 2.6.7

# set ruby/rails vars
export RAILS_ENV=production
export BUNDLE_PATH="vendor/bundle"

bundle config set --local path vendor/bundle
bundle install

bundle exec ruby -e 'print Gem.dir' > config/GEM_HOME
export GEM_HOME
GEM_HOME=$(cat config/GEM_HOME)

mkdir -p $YARN_CACHE
yarn install --frozen-lockfile --network-timeout 1000000 \
    --cache-folder $YARN_CACHE

# COMPILE_ASSETS_BRAND_CONFIGS variable:
# https://github.com/instructure/canvas-lms/issues/2023

COMPILE_ASSETS_BRAND_CONFIGS=0 COMPILE_ASSETS_NPM_INSTALL=0 \
    bundle exec rails canvas:compile_assets
chown -R www-data:www-data $WEBROOT/public/dist/brandable_css

# apply another patch; this time to the init script
_patch=/usr/local/src/canvas_init.patch
git apply $_patch
install -D -m 0644 "$_patch" \
    /usr/local/share/turnkey-canvas/canvas_init.patch
rm -f "$_patch"

bundle exec rake db:initial_setup
bundle exec rake db:migrate

# resolve (errant) 'failed to allocate memory' issue - closes
# https://github.com/turnkeylinux/tracker/issues/1965
bundle exec rake switchman_inst_jobs:install:migrations

mkdir -p log tmp/pids public/assets 

# stop services
service postgresql stop
service redis-server stop

unset http_proxy

# clean out installation log
rm -f $WEBROOT/log/*
rm -rf $YARN_CACHE
