#!/bin/bash -ex

# disable Apache mod_evasive for now - see
# https://github.com/turnkeylinux/tracker/issues/1965
a2dismod evasive

source /usr/local/src/canvas.conf
YARN_CACHE=/var/cache/yarn
export RAILS_ENV=production
export BUNDLE_PATH="vendor/bundle"

# preset answers for automated install
export CANVAS_LMS_ADMIN_EMAIL=$ADMIN_MAIL
export CANVAS_LMS_ADMIN_PASSWORD=$ADMIN_PASS
export CANVAS_LMS_ACCOUNT_NAME="TurnKey super admin"
export CANVAS_LMS_STATS_COLLECTION="opt-out"

# set lang to quieten down install
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# install canvas, populate database and compile assets
service redis-server start
[[ "$FAB_HTTP_PROXY" ]] && export http_proxy=$FAB_HTTP_PROXY
[[ "$FAB_HTTPS_PROXY" ]] && export https_proxy=$FAB_HTTPS_PROXY

cd $WEBROOT

# canvas needs specific version of bundler - see
# https://github.com/instructure/canvas-lms/wiki/Production-Start#bundler-and-canvas-dependencies
gem install bundler --version 2.5.10

bundle config set --local path $BUNDLE_PATH
bundle config set without 'mysql sqlite'
bundle install

bundle exec gem env home > config/GEM_HOME
export GEM_HOME=$(cat config/GEM_HOME)

yarn config set strict-ssl false
npm install -g yarn@1.22.19 wsrun
mkdir -p $YARN_CACHE
yarn install --network-timeout 1000000 --scripts-prepend-node-path --cache-folder $YARN_CACHE

# COMPILE_ASSETS_BRANC_CONFIGS variable:
# https://github.com/instructure/canvas-lms/issues/2023
COMPILE_ASSETS_BRAND_CONFIGS=0 bundle exec rake canvas:compile_assets
chown -R www-data:www-data $WEBROOT/public/dist/brandable_css

# patch init script
_patch=/usr/local/src/canvas_init.patch
git apply $_patch

bundle exec rake db:initial_setup
bundle exec rake db:migrate

mkdir -p log tmp/pids public/assets 

# stop services
service postgresql stop
service redis-server stop

unset http_proxy https_proxy

# clean out installation log & cache
rm -f $WEBROOT/log/*
rm -rf $YARN_CACHE
