#!/bin/bash -ex

source /usr/local/src/canvas.conf

YARN_CACHE=/var/cache/yarn

# preset answers for automated install
export CANVAS_LMS_ADMIN_EMAIL=$ADMIN_MAIL
export CANVAS_LMS_ADMIN_PASSWORD=$ADMIN_PASS
export CANVAS_LMS_ACCOUNT_NAME="TurnKey Canvas"
export CANVAS_LMS_STATS_COLLECTION="opt-out"

# set lang to quieten down install
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# install canvas, populate database and compile assets
service redis-server start
[ "$FAB_HTTP_PROXY" ] && export http_proxy=$FAB_HTTP_PROXY

cd $WEBROOT

# canvas needs specific version of bundler - see
# https://github.com/instructure/canvas-lms/wiki/Production-Start#bundler-and-canvas-dependencies
gem install bundler --version 2.2.15

# set ruby/rails vars
export GEM_HOME=$(cat config/GEM_HOME)
export RAILS_ENV=production
export BUNDLE_PATH="vendor/bundle"

bundle config set without 'mysql sqlite'
bundle install

mkdir -p $YARN_CACHE
yarn install ---scripts-prepend-node-path --network-concurrency 1 --cache-folder $YARN_CACHE

CANVAS_BUILD_CONCURRENCY=1 bundle exec rake canvas:compile_assets

# apply patch to work around install issue; see
# https://groups.google.com/g/canvas-lms-users/c/A5l8B84SezM
_patch=/usr/local/src/app_models_course.rb.patch
git apply $_patch
rm -rf $_patch

# apply another patch; this time to the init script
_patch=/usr/local/src/canvas_init.patch
git apply $_patch
rm -rf $_patch

bundle exec rake db:initial_setup

cd gems/canvas_i18nliner/
npm install --unsafe-perm
cd -

mkdir -p log tmp/pids public/assets 

# stop services
service postgresql stop
service redis-server stop

unset http_proxy

# clean out installation log
rm -f $WEBROOT/log/*
rm -rf $YARN_CACHE
