#!/bin/bash -ex

source /usr/local/src/canvas.conf

# setup automated jobs
echo $(gem env home) > $WEBROOT/config/GEM_HOME
ln -s $WEBROOT/script/canvas_init /etc/init.d/canvas_init

# changes applied with patch in overlays/usr/local/src/canvas_init.patch
# during conf.d/55canvas-install
# sed -i '/exec su/ s#$# -s /bin/bash#' $WEBROOT/script/canvas_init
# sed -i "s|exec script\/delayed_job \$@|bundle exec script\/delayed_job \$\@|" $WEBROOT/script/canvas_init

update-rc.d canvas_init defaults
