#!/bin/bash -ex

WEBROOT=/var/www/canvas
RCE_ROOT=/var/www/canvas-rce-api
source /usr/local/src/canvas.conf

BUNDLE_PATH="$WEBROOT/vendor/bundle"
GEM_PATH="$(cat "$WEBROOT/config/GEM_HOME")"

if [[ -z "$BUNDLE_PATH" ]] || [[ ! -d "$BUNDLE_PATH" ]]; then
    echo "Fatal: BUNDLE_PATH ($BUNDLE_PATH) does not exist"
    exit 1
fi
if [[ -z "$GEM_PATH" ]] || [[ ! -d "$GEM_PATH" ]]; then
    echo "Fatal: GEM_PATH ($GEM_PATH)  does not exist"
    exit 1
fi

APACHE_CONF=/etc/apache2/sites-available/canvas.conf
sed -i "/BUNDLE_PATH/ s|__BUNDLE_PATH__|$BUNDLE_PATH|" "$APACHE_CONF"
sed -i "/GEM_PATH/ s|__GEM_PATH__|$GEM_PATH|" "$APACHE_CONF"
a2ensite canvas

# create convenience symlink for logs
rm -rf /var/log/canvas
ln -s $WEBROOT/log /var/log/canvas

chown -R root:www-data "$WEBROOT/config"
chown root:www-data "$WEBROOT/Gemfile.lock" "$WEBROOT/config.ru" \
    "$WEBROOT/config/environment.rb"
find "$WEBROOT/config" -type d -exec chmod 0750 {} \;
find "$WEBROOT/config" -type f -name '*.yml' -exec chmod 0440 {} \;
chown -R www-data:www-data "$WEBROOT/log" "$WEBROOT/tmp"

chown -R root:root "$RCE_ROOT"
chown -R www-data:www-data "$RCE_ROOT/tmp"
chown root:www-data "$RCE_ROOT/.env"
chmod 0440 "$RCE_ROOT/.env"

# fix for github.com/phusion/passenger/wiki/Debugging-application-startup-problems
echo "PassengerStartTimeout 300" >> /etc/apache2/mods-available/passenger.conf

# part of fix for https://github.com/phusion/passenger/issues/2397
echo "PassengerInstanceRegistryDir /run/passenger-instreg" >> /etc/apache2/mods-available/passenger.conf
# see also /etc/tmpfiles.d/passenger.conf in overlay

install -d /usr/local/share/turnkey-canvas
cat > /usr/local/share/turnkey-canvas/source <<EOF
version=$CANVAS_VERSION
canvas_channel=prod
canvas_commit=$CANVAS_COMMIT
canvas_tree=$CANVAS_TREE
canvas_archive_sha256=$CANVAS_SHA256
rce_channel=master
rce_commit=$RCE_COMMIT
rce_tree=$RCE_TREE
rce_archive_sha256=$RCE_SHA256
ruby=$(ruby -e 'print RUBY_VERSION')
rails=$(cd "$WEBROOT" && BUNDLE_PATH=vendor/bundle bundle exec rails --version | awk '{print $2}')
node=$(node --version)
yarn=$(yarn --version)
yarn_source=official-yarn-apt
EOF
chmod 0644 /usr/local/share/turnkey-canvas/source

rm -f /usr/local/src/canvas.conf
