#!/bin/bash -ex

WEBROOT=/var/www/canvas

BUNDLE_PATH="$WEBROOT/vendor/bundle"
GEM_PATH="$(cat "$WEBROOT/config/GEM_HOME")"

if [[ -z "$BUNDLE_PATH" ]] || [[ ! -d "$BUNDLE_PATH" ]]; then
    echo "Fatal: BUNDLE_PATH ($BUNDLE_PATH) does not exist"
fi
if [[ -z "$GEM_PATH" ]] || [[ ! -d "$GEM_PATH" ]]; then
    echo "Fatal: GEM_PATH ($GEM_PATH)  does not exist"
fi

APACHE_CONF=/etc/apache2/sites-available/canvas.conf
sed -i "/BUNDLE_PATH/ s|__BUNDLE_PATH__|$BUNDLE_PATH|" "$APACHE_CONF"
sed -i "/GEM_PATH/ s|__GEM_PATH__|$GEM_PATH|" "$APACHE_CONF"

PASSGR_CONF=/etc/apache2/mods-available/passenger.conf
echo "PassengerStartTimeout 300" >> $PASSGR_CONF
# part of fix for https://github.com/phusion/passenger/issues/2397
# other part in /etc/tmpfiles.d/passenger.conf (overlay)
echo "PassengerInstanceRegistryDir /run/passenger-instreg" >> $PASSGR_CONF

# create convenience symlink for logs
rm -rf /var/log/canvas
ln -s $WEBROOT/log /var/log/canvas

chown -R www-data:www-data $WEBROOT/{config,log}
chmod 400 $WEBROOT/config/cache_store.yml

py3clean /
yarn cache clean

rm -f /usr/local/src/canvas.conf
