#!/bin/sh -ex

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/canvas

# get db_pass and delete template rails app
DB_NAME=canvas
DB_USER=canvas
DB_PASS=$(grep password: $WEBROOT/config/database.yml | head -n 1 | awk '{print $2}')
rm -rf $WEBROOT

# unpack into webroot
tar -zxf $SRC/instructure-canvas-*.tar.gz -C $(dirname $WEBROOT)
rm $SRC/instructure-canvas-*.tar.gz
mv $(dirname $WEBROOT)/instructure-canvas-* $WEBROOT

# start mysql
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# setup database config and create queue dbs
for DB_ENV in test development production; do
DB_QUEUE=${DB_NAME}_queue_${DB_ENV}
cat >>$WEBROOT/config/database.yml<<EOF
$DB_ENV:
  adapter: mysql
  encoding: utf8
  database: ${DB_NAME}_${DB_ENV}
  host: localhost
  username: $DB_USER
  password: $DB_PASS
  timeout: 5000
  queue:
    adapter: mysql
    encoding: utf8
    database: $DB_QUEUE
    host: localhost
    username: $DB_USER
    password: $DB_PASS
    timeout: 5000

EOF

$MYSQL_ADMIN create $DB_QUEUE
$MYSQL_BATCH --execute "grant all privileges on $DB_QUEUE.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
done

# configure email
cat >$WEBROOT/config/outgoing_mail.yml<<EOF
test:
  delivery_method: "test"

development:
  address: "localhost"
  port: "25"
  domain: "$DOMAIN"
  outgoing_address: "$ADMIN_MAIL"
  default_name: "TurnKey Canvas"

production:
  address: "localhost"
  port: "25"
  domain: "$DOMAIN"
  outgoing_address: "$ADMIN_MAIL"
  default_name: "TurnKey Canvas"
EOF

# configure domain
cat >$WEBROOT/config/domain.yml<<EOF
test:
  domain: "$DOMAIN"

development:
  domain: "$DOMAIN"

production:
  domain: "$DOMAIN"
  ssl: true
EOF

# stop services
/etc/init.d/mysql stop

