#!/bin/bash -e
# regenerate Canvas secrets

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# Canvas Rich Content Editor API keys
ENV_FILE=/var/www/canvas-rce-api/.env
DYNAMIC_SETTINGS=/var/www/canvas/config/dynamic_settings.yml

SECRET=$(mcookie)
KEY=$(mcookie)

sed -i "s|ECOSYSTEM_KEY=.*|ECOSYSTEM_KEY=\"$SECRET\"|" $ENV_FILE
sed -i "s|ECOSYSTEM_SECRET=.*|ECOSYSTEM_SECRET=\"$KEY\"|" $ENV_FILE
sed -i "s|CIPHER_PASSWORD=.*|CIPHER_PASSWORD=\"$(mcookie)\"|" $ENV_FILE
sed -i "s|signing-secret: .*|signing-secret: \"$KEY\"|" $DYNAMIC_SETTINGS
sed -i "s|encryption-secret: .*|encryption-secret: \"$SECRET\"|" $DYNAMIC_SETTINGS

# Perhaps should restart apache (mod_passenger) here? Canvas is so slow to
# start though, will just do it in interactive hook (rather than twice).
