#!/bin/bash -e
# set canvas admin password, email and domain to serve

. /etc/default/inithooks

[ -e "$INITHOOKS_CONF" ] && . "$INITHOOKS_CONF"

printf '%s' "$APP_PASS" \
    | "$INITHOOKS_PATH/bin/canvas.py" --pass-stdin \
        --email="$APP_EMAIL" --domain="$APP_DOMAIN"
