# central configuration and functions used by conf.d scripts

export CANVAS_VERSION=2026-04-22
export CANVAS_COMMIT=44bfdc264d5fe6a942ebdb5f10a0eb63ee04df3a
export CANVAS_TREE=dd2a9caa6afe683108a493a13c32340e1b3ac5e6
export CANVAS_SHA256=2ca116f8a130b970c7b945fd547e760bdb8e7b8d0ea4c1c63f07222fd874009c
export RCE_COMMIT=e076fe28a09f4e41058da0983b5ef2c809123d9f
export RCE_TREE=4a2e99c1efccf0011215bb074065a0859135a132
export RCE_SHA256=1b36c2231c09d406053c92fde9d805211e538265e8d01827477a3ce9187c0495

export SRC=/usr/local/src
export WEBROOT=/var/www/canvas

export ADMIN_PASS=turnkey1
export ADMIN_MAIL=admin@example.com
export DOMAIN=www.example.com

export DB_USER=canvas
export DB_PASS= # will be updated by conf.d/30rails
export DB_NAME=canvas_production
export DB_QUEUE=canvas_queue_production

download() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}
